patterns:
    - markers: ['WARNING', 'ELAPSED']
      re: ['\d{1,2}-\w{3}-\d{4}', '\d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}', '\d{1,4}', '\d*ms']
    - markers: ['ELAPSED']
      re: ['\d*ms']

    #  - markers: ['WARNING', 'ELAPSED']
    #  re: ['\d{1,2}-\w{3}-\d{4}', '\d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}', '\d{1,4}', '\d*ms']
    #- markers: ['ELAPSED']
    #  re: ['\d{1,2}-\w{3}-\d{4}', '\d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}', '\d{1,4}', '\d*ms']